# Generated by Django 4.2.5 on 2023-10-12 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration_Login', '0013_departmentregister_details_dept_content_and_more'),
        ('DM_Head', '0004_allocation_details_previos_allocation_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleave',
            name='no_of_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='previos_allocation_details',
            name='newallocation_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration_Login.employeeregister_details'),
        ),
    ]
