# Generated by Django 4.2.5 on 2023-10-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DM_Head', '0005_employeeleave_no_of_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleave',
            name='leave_statuChange_date',
            field=models.DateField(null=True),
        ),
    ]
