# Generated by Django 4.2.5 on 2023-10-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DM_Head', '0006_employeeleave_leave_statuchange_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work_Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('task_discription', models.TextField(blank=True, default='', null=True)),
                ('task_add_time', models.TimeField(auto_now_add=True, null=True)),
                ('task_status', models.IntegerField(default=0)),
                ('task_add_date', models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
