# Generated by Django 4.2.5 on 2023-10-17 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DM_Head', '0008_work_task_comp_taskid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('client_email_primary', models.EmailField(blank=True, default='client@gmail.com', max_length=254, null=True)),
                ('client_email_alter', models.EmailField(blank=True, default='client@gmail2.com', max_length=254, null=True)),
                ('client_phone', models.CharField(blank=True, default='9000000009', max_length=255, null=True)),
                ('client_phone_alter', models.CharField(blank=True, default='9800000089', max_length=255, null=True)),
                ('client_address1', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('client_address2', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('client_address3', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('client_pincode', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('client_district', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('client_state', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('client_profile', models.ImageField(default='', upload_to='client\\profile')),
                ('client_bussiness_email_primary', models.EmailField(blank=True, default='client@gmail.com', max_length=254, null=True)),
                ('client_bussiness_email_alter', models.EmailField(blank=True, default='client@gmail2.com', max_length=254, null=True)),
                ('client_bussiness_phone', models.CharField(blank=True, default='9000000009', max_length=255, null=True)),
                ('client_bussiness_website', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('client_bussiness_phone_alter', models.CharField(blank=True, default='9800000089', max_length=255, null=True)),
                ('client_bussiness_address1', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('client_bussiness_address2', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('client_bussiness_address3', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('client_bussiness_pincode', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('client_bussiness_district', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('client_bussiness_state', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('client_bussiness_file', models.FileField(default='', upload_to='client\x0ciles')),
                ('bussiness_logo', models.ImageField(default='', upload_to='client\\logo')),
                ('more_discription', models.TextField(blank=True, default='', null=True)),
                ('client_add_time', models.TimeField(auto_now_add=True, null=True)),
                ('client_status', models.IntegerField(default=0)),
                ('client_reg_date', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_discription', models.TextField(blank=True, default='', null=True)),
                ('work_create_time', models.TimeField(auto_now_add=True, null=True)),
                ('work_file', models.FileField(default='', upload_to='work\x0ciles')),
                ('work_progress', models.IntegerField(default=0)),
                ('work_allocate_status', models.IntegerField(default=0)),
                ('work_status', models.IntegerField(default=0)),
                ('work_create_date', models.DateField(null=True)),
                ('work_end_date', models.DateField(null=True)),
                ('clientId', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='DM_Head.clientregister')),
            ],
        ),
        migrations.CreateModel(
            name='ClientTask_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_discription', models.TextField(blank=True, default='', null=True)),
                ('task_file', models.FileField(default='', upload_to='work\task\x0ciles')),
                ('task_allocate_status', models.IntegerField(default=0)),
                ('task_status', models.IntegerField(default=0)),
                ('task_create_date', models.DateField(null=True)),
                ('client_Id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='DM_Head.clientregister')),
                ('work_Id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='DM_Head.workregister')),
            ],
        ),
    ]
