# Generated by Django 4.2.5 on 2023-10-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration_Login', '0013_departmentregister_details_dept_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designationregister_details',
            name='dashboard_id',
            field=models.IntegerField(default=0),
        ),
    ]
