# Generated by Django 4.2.5 on 2023-10-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration_Login', '0014_designationregister_details_dashboard_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeregister_details',
            name='emp_regId',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
